export const CHURCH_DEFAULTS = {
  name: "Igreja Renascendo em Cristo",
  shortName: "Renascendo",
  pastor: "Pr. Presidente Wellington Felicio Vieira",
  email: "sede.renascendoemcristo@gmail.com",
  phone: "(62) 99154-2563",
  cnpj: "58.563.268/0001-11",
  addressLine: "R. Nicanor Albernaz, Qd. 02, Lt. 01",
  neighborhood: "Setor Cristina",
  city: "Trindade",
  state: "GO",
  cep: "75.383-579",
  addressFull:
    "R NICANOR ALBERNAZ QD. 02 LT. 01 - SETOR CRISTINA - TRINDADE - GO. CEP: 75.383-579",
};

export const STATUSES = [
  { id: "ativo", label: "Ativo" },
  { id: "congregado", label: "Congregado" },
  { id: "inativo", label: "Inativo" },
  { id: "transferido", label: "Transferido" },
  { id: "disciplina", label: "Em disciplina" },
  { id: "falecido", label: "Falecido" },
] as const;

export const KINSHIP_TYPES = [
  { id: "conjuge", label: "Cônjuge" },
  { id: "filho", label: "Filho(a)" },
  { id: "pai", label: "Pai" },
  { id: "mae", label: "Mãe" },
  { id: "irmao", label: "Irmão(ã)" },
  { id: "avo", label: "Avô/Avó" },
  { id: "neto", label: "Neto(a)" },
  { id: "sogro", label: "Sogro(a)" },
  { id: "genro", label: "Genro/Nora" },
  { id: "tio", label: "Tio(a)" },
  { id: "primo", label: "Primo(a)" },
  { id: "sobrinho", label: "Sobrinho(a)" },
  { id: "outro", label: "Outro" },
] as const;

export const GENDERS = ["Feminino", "Masculino", "Não informar"] as const;

export const MARITAL_STATUSES = [
  "Solteiro(a)",
  "Casado(a)",
  "União estável",
  "Viúvo(a)",
  "Divorciado(a)",
  "Separado(a)",
] as const;

export const ECCLESIASTICAL_TITLES = [
  "Pastor Presidente",
  "Pastor",
  "Pastora",
  "Bispo",
  "Evangelista",
  "Presbítero",
  "Diácono",
  "Diaconisa",
  "Missionário",
  "Missionária",
  "Cooperador",
  "Cooperadora",
  "Obreiro",
  "Obreira",
];

export const LOCAL_TITLES = [
  "Dirigente de culto",
  "Líder de jovens",
  "Líder de crianças",
  "Líder de mulheres",
  "Líder de homens",
  "Líder de casais",
  "Líder de célula",
  "Regente de louvor",
  "Cantor",
  "Músico",
  "Sonoplasta",
  "Mídia",
  "Tesoureiro",
  "Secretário",
  "Professor da EBD",
  "Intercessor",
  "Porteiro",
  "Recepção",
  "Zelador",
  "Coordenador de missões",
  "Diácono de patrimônio",
];

export const SERVICE_TITLES = [
  "Culto de Celebração",
  "Culto de Doutrina",
  "Culto de Ensino",
  "Culto de Jovens",
  "Culto de Mulheres",
  "Culto de Homens",
  "Culto Infantil",
  "Santa Ceia",
  "Vigília",
  "Culto de Oração",
  "Culto de Missões",
  "Conferência",
  "Batismo",
  "Ensaio de Louvor",
];

export const CHANGE_TYPES = [
  { id: "criacao", label: "Criação" },
  { id: "atualizacao", label: "Atualização cadastral" },
  { id: "foto", label: "Foto" },
  { id: "parentesco", label: "Parentesco" },
  { id: "cargo_eclesiastico", label: "Cargo eclesiástico" },
  { id: "cargo_local", label: "Cargo local" },
  { id: "status", label: "Status" },
] as const;

export const FIELD_LABELS: Record<string, string> = {
  fullName: "Nome",
  birthDate: "Nascimento",
  gender: "Gênero",
  maritalStatus: "Estado civil",
  phone: "Telefone",
  email: "E-mail",
  cpf: "CPF",
  address: "Endereço",
  neighborhood: "Bairro",
  city: "Cidade",
  baptismDate: "Batismo",
  conversionDate: "Conversão",
  memberSince: "Membro desde",
  notes: "Observações",
  status: "Status",
  kinshipType: "Parentesco",
  kinshipMemberId: "Pessoa vinculada",
  kinshipNotes: "Observação do parentesco",
  title: "Cargo",
  consecrationDate: "Data de consagração",
  startDate: "Data inicial",
  endDate: "Data final",
  foto: "Foto",
  tipo: "Tipo",
  pessoa: "Pessoa",
  observacao: "Observação",
};

export const CADASTRAL_FIELDS = [
  "fullName",
  "birthDate",
  "gender",
  "maritalStatus",
  "phone",
  "email",
  "cpf",
  "address",
  "neighborhood",
  "city",
  "baptismDate",
  "conversionDate",
  "memberSince",
  "notes",
] as const;
